--- #YAML:1.0
name: CGI-Application-Plugin-Config-Simple
version: 1.00
author:
  - Michael Peters <mpeters@plusthree.com>
abstract: Add Config::Simple support to CGI::Application
license: perl
generated_by: Module::Build version 0.2604, without YAML.pm
